version: '3.8'

services:
  softwareengineer_test_task:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: softwareengineer_test_task
    entrypoint: php -S 0.0.0.0:8083
    volumes:
    - ./:/var/www
    - type: volume
      source: Contract
      target: /var/www/Contract
    ports:
    - 8083:8083
    command: /bin/bash


volumes:
  Contract: