version: '3.8'

services:
  softwareengineer_test_task_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: softwareengineer_test_task_server
    command: php -S 0.0.0.0:8084
    volumes:
    - ./:/var/www
  softwareengineer_test_task:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: softwareengineer_test_task
    volumes:
      - ./:/var/www
