version: '3.8'

services:
  softwareengineer_test_task:
    build:
      context: .
      dockerfile: client.Dockerfile
    container_name: softwareengineer_test_task
    volumes:
      - type: volume
        source: src
        target: /var/www/src
  softwareengineer_test_task_server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - 8084:80
    volumes:
      - .:/var/www/html/
      - /var/www/html/vendor/
      - type: volume
        source: src
        target: /var/www/html/src

volumes:
  src:
