<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CategoryWeights.proto

namespace CategoryWeights;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>categoryWeights.Category</code>
 */
class Category extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string category_name = 1;</code>
     */
    protected $category_name = '';
    /**
     * Generated from protobuf field <code>float ratings = 2;</code>
     */
    protected $ratings = 0.0;
    /**
     * Generated from protobuf field <code>repeated .categoryWeights.Score score_for_date = 3;</code>
     */
    private $score_for_date;
    /**
     * Generated from protobuf field <code>.categoryWeights.Score overall_score = 4;</code>
     */
    protected $overall_score = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $category_name
     *     @type float $ratings
     *     @type \CategoryWeights\Score[]|\Google\Protobuf\Internal\RepeatedField $score_for_date
     *     @type \CategoryWeights\Score $overall_score
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CategoryWeights::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string category_name = 1;</code>
     * @return string
     */
    public function getCategoryName()
    {
        return $this->category_name;
    }

    /**
     * Generated from protobuf field <code>string category_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryName($var)
    {
        GPBUtil::checkString($var, True);
        $this->category_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float ratings = 2;</code>
     * @return float
     */
    public function getRatings()
    {
        return $this->ratings;
    }

    /**
     * Generated from protobuf field <code>float ratings = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setRatings($var)
    {
        GPBUtil::checkFloat($var);
        $this->ratings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .categoryWeights.Score score_for_date = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getScoreForDate()
    {
        return $this->score_for_date;
    }

    /**
     * Generated from protobuf field <code>repeated .categoryWeights.Score score_for_date = 3;</code>
     * @param \CategoryWeights\Score[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setScoreForDate($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CategoryWeights\Score::class);
        $this->score_for_date = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.categoryWeights.Score overall_score = 4;</code>
     * @return \CategoryWeights\Score|null
     */
    public function getOverallScore()
    {
        return isset($this->overall_score) ? $this->overall_score : null;
    }

    public function hasOverallScore()
    {
        return isset($this->overall_score);
    }

    public function clearOverallScore()
    {
        unset($this->overall_score);
    }

    /**
     * Generated from protobuf field <code>.categoryWeights.Score overall_score = 4;</code>
     * @param \CategoryWeights\Score $var
     * @return $this
     */
    public function setOverallScore($var)
    {
        GPBUtil::checkMessage($var, \CategoryWeights\Score::class);
        $this->overall_score = $var;

        return $this;
    }

}

