<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Scoring.proto

namespace Scoring;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>scoring.CategoryScore</code>
 */
class CategoryScore extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string CategoryName = 1;</code>
     */
    protected $CategoryName = '';
    /**
     * Generated from protobuf field <code>int32 Score = 2;</code>
     */
    protected $Score = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $CategoryName
     *     @type int $Score
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Scoring::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string CategoryName = 1;</code>
     * @return string
     */
    public function getCategoryName()
    {
        return $this->CategoryName;
    }

    /**
     * Generated from protobuf field <code>string CategoryName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryName($var)
    {
        GPBUtil::checkString($var, True);
        $this->CategoryName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Score = 2;</code>
     * @return int
     */
    public function getScore()
    {
        return $this->Score;
    }

    /**
     * Generated from protobuf field <code>int32 Score = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setScore($var)
    {
        GPBUtil::checkInt32($var);
        $this->Score = $var;

        return $this;
    }

}

