<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Scoring.proto

namespace Scoring;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>scoring.Date</code>
 */
class Date extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 Date = 1;</code>
     */
    protected $Date = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $Date
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Scoring::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 Date = 1;</code>
     * @return int|string
     */
    public function getDate()
    {
        return $this->Date;
    }

    /**
     * Generated from protobuf field <code>int64 Date = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDate($var)
    {
        GPBUtil::checkInt64($var);
        $this->Date = $var;

        return $this;
    }

}

