<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Scoring.proto

namespace Scoring;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>scoring.ScoreByCategory</code>
 */
class ScoreByCategory extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.scoring.CategoryScore CategoryScore = 1;</code>
     */
    protected $CategoryScore = null;
    /**
     * Generated from protobuf field <code>int32 Ratings = 2;</code>
     */
    protected $Ratings = 0;
    /**
     * Generated from protobuf field <code>repeated .scoring.DateScore DateScores = 3;</code>
     */
    private $DateScores;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Scoring\CategoryScore $CategoryScore
     *     @type int $Ratings
     *     @type \Scoring\DateScore[]|\Google\Protobuf\Internal\RepeatedField $DateScores
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Scoring::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.scoring.CategoryScore CategoryScore = 1;</code>
     * @return \Scoring\CategoryScore|null
     */
    public function getCategoryScore()
    {
        return isset($this->CategoryScore) ? $this->CategoryScore : null;
    }

    public function hasCategoryScore()
    {
        return isset($this->CategoryScore);
    }

    public function clearCategoryScore()
    {
        unset($this->CategoryScore);
    }

    /**
     * Generated from protobuf field <code>.scoring.CategoryScore CategoryScore = 1;</code>
     * @param \Scoring\CategoryScore $var
     * @return $this
     */
    public function setCategoryScore($var)
    {
        GPBUtil::checkMessage($var, \Scoring\CategoryScore::class);
        $this->CategoryScore = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Ratings = 2;</code>
     * @return int
     */
    public function getRatings()
    {
        return $this->Ratings;
    }

    /**
     * Generated from protobuf field <code>int32 Ratings = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRatings($var)
    {
        GPBUtil::checkInt32($var);
        $this->Ratings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .scoring.DateScore DateScores = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDateScores()
    {
        return $this->DateScores;
    }

    /**
     * Generated from protobuf field <code>repeated .scoring.DateScore DateScores = 3;</code>
     * @param \Scoring\DateScore[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDateScores($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Scoring\DateScore::class);
        $this->DateScores = $arr;

        return $this;
    }

}

