<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Scoring.proto

namespace Scoring;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>scoring.ScoreByTicket</code>
 */
class ScoreByTicket extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 TicketId = 1;</code>
     */
    protected $TicketId = 0;
    /**
     * Generated from protobuf field <code>repeated .scoring.CategoryScore CategoryScores = 2;</code>
     */
    private $CategoryScores;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $TicketId
     *     @type \Scoring\CategoryScore[]|\Google\Protobuf\Internal\RepeatedField $CategoryScores
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Scoring::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 TicketId = 1;</code>
     * @return int
     */
    public function getTicketId()
    {
        return $this->TicketId;
    }

    /**
     * Generated from protobuf field <code>int32 TicketId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTicketId($var)
    {
        GPBUtil::checkInt32($var);
        $this->TicketId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .scoring.CategoryScore CategoryScores = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCategoryScores()
    {
        return $this->CategoryScores;
    }

    /**
     * Generated from protobuf field <code>repeated .scoring.CategoryScore CategoryScores = 2;</code>
     * @param \Scoring\CategoryScore[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCategoryScores($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Scoring\CategoryScore::class);
        $this->CategoryScores = $arr;

        return $this;
    }

}

