<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Scoring.proto

namespace Scoring;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>scoring.ScoresByTickets</code>
 */
class ScoresByTickets extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .scoring.ScoreByTicket ScoresByTickets = 1;</code>
     */
    private $ScoresByTickets;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Scoring\ScoreByTicket[]|\Google\Protobuf\Internal\RepeatedField $ScoresByTickets
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Scoring::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .scoring.ScoreByTicket ScoresByTickets = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getScoresByTickets()
    {
        return $this->ScoresByTickets;
    }

    /**
     * Generated from protobuf field <code>repeated .scoring.ScoreByTicket ScoresByTickets = 1;</code>
     * @param \Scoring\ScoreByTicket[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setScoresByTickets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Scoring\ScoreByTicket::class);
        $this->ScoresByTickets = $arr;

        return $this;
    }

}

