<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Scoring.proto

namespace Scoring;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>scoring.ScoresByCategories</code>
 */
class ScoresByCategories extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .scoring.ScoreByCategory ScoresByCategories = 1;</code>
     */
    private $ScoresByCategories;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Scoring\ScoreByCategory[]|\Google\Protobuf\Internal\RepeatedField $ScoresByCategories
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Scoring::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .scoring.ScoreByCategory ScoresByCategories = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getScoresByCategories()
    {
        return $this->ScoresByCategories;
    }

    /**
     * Generated from protobuf field <code>repeated .scoring.ScoreByCategory ScoresByCategories = 1;</code>
     * @param \Scoring\ScoreByCategory[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setScoresByCategories($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Scoring\ScoreByCategory::class);
        $this->ScoresByCategories = $arr;

        return $this;
    }

}

